#!/bin/bash

#SBATCH --job-name=single_Illumina      ## Name of the job.
#SBATCH -A grylee_lab     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=8    ## number of cores the job needs
#SBATCH --error=slurm-%J.err ## error log file
#SBATCH -t 4-20:00:00

module load trimgalore/0.6.6
module load bwa/0.7.17
module load samtools/1.10
module load gatk/4.1.9.0
module load fastqc/0.11.9

#### call within-strain residule heterozygous sites 
id=A7
reads_1="${id}-READ1-Sequences.txt"
reads_2="${id}-READ2-Sequences.txt"
trim_reads_1="${reads_1}_val_1.fq"
trim_reads_2="${reads_2}_val_2.fq"

gunzip raw_reads/${id}-READ1-Sequences.txt.gz
gunzip raw_reads/${id}-READ2-Sequences.txt.gz

trim_galore --pair raw_reads/${reads_1} raw_reads/${reads_2} --fastqc
bwa mem -t 24 /dfs7/grylee/yuhenh3/recombination_rate/${id}_genomic.fna ${trim_reads_1} ${trim_reads_2} | samtools sort -@24 -o output_${id}_${id}_sorted.bam

gatk MarkDuplicates -I output_${id}_${id}_sorted.bam -O ${id}_${id}_marked_duplicates.bam -M ${id}_${id}_marked_dup_metrics.txt --SORTING_COLLECTION_SIZE_RATIO 0.1
gatk AddOrReplaceReadGroups I=${id}_${id}_marked_duplicates.bam O=${id}_${id}_reads_with_RG.bam SORT_ORDER=coordinate RGID=foo RGLB=bar RGPL=illumina RGPU=unit1 RGSM=Sample1 CREATE_INDEX=True

gatk HaplotypeCaller -I ${id}_${id}_reads_with_RG.bam -R /dfs7/grylee/yuhenh3/recombination_rate/${id}_genomic.fna -O ${id}_${id}_genomic_sorted.g.vcf.gz
gunzip ${id}_${id}_genomic_sorted.g.vcf.gz

#### call SNPs in each of F2 single fly Illumina sequences
for id in 2 3 4 5 7 8 9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 27 28 29 30 31 33 34 35 37 38 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 63 65 66 67 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 90 91 92 93 94 95 96 97 98 99 100 101 103 104 105 106 107 108 110 111 113 114 115 116 117 118 119 120 121 122 124 125 126 127 128 129 130 131 132 133 134 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 161 162 163 164 165 166 168 169 170 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 193 194 195 196 198 199 200 201 202 203 204 205 206 207 209 210 211 212 213 214 215
do
reads_1="${id}-READ1-Sequences.txt"
reads_2="${id}-READ2-Sequences.txt"
trim_reads_1="${reads_1}_val_1.fq"
trim_reads_2="${reads_2}_val_2.fq"

gunzip raw_reads/${id}-READ1-Sequences.txt.gz
gunzip raw_reads/${id}-READ2-Sequences.txt.gz

trim_galore --pair raw_reads/${reads_1} raw_reads/${reads_2} --fastqc
bwa mem -t 24 /dfs7/grylee/yuhenh3/recombination_rate/A6_genomic.fna ${trim_reads_1} ${trim_reads_2} | samtools sort -@24 -o output_${id}_A6_sorted.bam

gatk MarkDuplicates -I output_${id}_A6_sorted.bam -O ${id}_A6_marked_duplicates.bam -M ${id}_A6_marked_dup_metrics.txt --SORTING_COLLECTION_SIZE_RATIO 0.1
samtools depth ${id}_A6_marked_duplicates.bam > ${id}_A6_marked_duplicates_depth.txt
gatk AddOrReplaceReadGroups I=${id}_A6_marked_duplicates.bam O=${id}_A6_reads_with_RG.bam SORT_ORDER=coordinate RGID=foo RGLB=bar RGPL=illumina RGPU=unit1 RGSM=Sample1 CREATE_INDEX=True

gatk HaplotypeCaller -I ${id}_A6_reads_with_RG.bam -R /dfs7/grylee/yuhenh3/recombination_rate/A6_genomic.fna -O ${id}_A6_genomic_sorted.g.vcf.gz
gunzip ${id}_A4_genomic_sorted.g.vcf.gz

done
