#!/bin/bash

#SBATCH --job-name=single_Pacbio      ## Name of the job.
#SBATCH -A grylee_lab     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=32    ## number of cores the job needs max 64
#SBATCH --error=slurm-%J.err ## error log file
#SBATCH -t 1-00:00:00

module load minimap2/2.23 

##You could install pbsim via mamba: mamba install pbsim2
pbsim --data-type CLR --depth 15 --length-max 200000 --model_qc model_qc_clr --length-mean 22000 --length-sd 2500 A6_A4_recombine_arms_each_CM010569.1.fasta  --prefix CM010569.1_15

pbsim --data-type CLR --depth 15 --length-max 200000 --model_qc model_qc_clr --length-mean 22000 --length-sd 2500 A6_A4_recombine_arms_each_CM010570.1.fasta  --prefix CM010570.1_15

pbsim --data-type CLR --depth 15 --length-max 200000 --model_qc model_qc_clr --length-mean 22000 --length-sd 2500 A6_A4_recombine_arms_each_CM010571.1.fasta  --prefix CM010571.1_15

pbsim --data-type CLR --depth 15 --length-max 200000 --model_qc model_qc_clr --length-mean 22000 --length-sd 2500 A6_A4_recombine_arms_each_CM010572.1.fasta  --prefix CM010572.1_15

pbsim --data-type CLR --depth 15 --length-max 200000 --model_qc model_qc_clr --length-mean 22000 --length-sd 2500 A6_A4_recombine_arms_each_CM010573.1.fasta  --prefix CM010573.1_15

perl obtain_PBSIM_reads_recombinant.pl
cat *15x.fastq > CO_reads_pbsim_15x.fastq

minimap2 -ax map-pb --secondary=no -t 32 A6_genomic.fna CO_reads_pbsim_15x.fastq > aln_A6_pbsim_CO_read_15x.sam
minimap2 -ax map-pb --secondary=no -t 32 A4_genomic.fna CO_reads_pbsim_15x.fastq > aln_A4_pbsim_CO_read_15x.sam

